from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

# API endpoints
urlpatterns = format_suffix_patterns([
    path('boards/',
        views.BoardList.as_view(),
        name='board-list'),
    path('boards/create/',
        views.BoardCreate.as_view(),
        name='board-create'),
    path('boards/<int:pk>/',
        views.BoardDetail.as_view(),
        name='board-detail'),
    path('boards/<int:board_id>/led-config/',
        views.LedConfigView.as_view(),
        name='led-config'),
    path('boards/<int:board_id>/boulders/',
        views.BoulderList.as_view(),
        name='board-boulders'),
    path('boulders/',
        views.BoulderList.as_view(),
        name='boulder-list'),
    path('boulders/<int:pk>/',
        views.BoulderDetail.as_view(),
        name='boulder-detail'),
    path('boulders/<int:boulder_id>/ascents/',
        views.BoulderAscentListCreate.as_view(),
        name='boulder-ascent-list-create'),
    path('boulders/<int:boulder_id>/like/',
        views.BoulderLikeView.as_view(),
        name='boulder-like'),
    path('users/',
        views.UserList.as_view(),
        name='user-list'),
    path('users/',
        views.UserList.as_view(),
        name='user-list'),
    path('users/<int:pk>/',
        views.UserDetail.as_view(),
        name='user-detail'),
    path('registration/',
        views.UserRegistration.as_view(),
        name='user-registration'),
])
