# Generated by Django 5.1.4 on 2025-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ascent",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
