# Generated by Django 5.1.4 on 2025-01-17 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
    ]
