# Generated by Django 5.1.4 on 2025-02-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.ImageField(null=True, upload_to="board_images/"),
        ),
        migrations.AlterField(
            model_name="board",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hold_data", models.JSONField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_config",
                        to="api.board",
                    ),
                ),
            ],
        ),
    ]
